### ISSUE TITLE
Nuget does not include Kentico js/css files to the project when restoring packages

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-mvc-component-starter#1]
### Brief bug description

Currently `/Kentico/**/*.js` and `/Kentico/**/*.css` files are a part of the repository. They should be restored as a part of the nuget (nuget package that contains them Kentico.AspNet.Mvc)

### Expected behavior

Files should be restored as a part of the nuget restore.

**Note** Remove the command from the [Get started](https://github.com/Kentico/ems-mvc-component-boilerplate#get-started) readme section

### Additional context

To get these files The workaround is to reinstall the nuget packages by the following command:

```sh
Update-Package -reinstall -Project Kentico.AspNet.Mvc`
```

**Comment by rpribyl** [comment]
Fixed here: https://github.com/Kentico/ems-mvc-component-starter/pull/6
