### ISSUE TITLE
Define best practices, how to distribute the components

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-mvc-component-starter#2]
### Motivation

Currently, there is no easy way, how to distribute the component as a nuget package.
Because as a part of the DLL is also the site cs files, that should not be there.

### Proposed solution

Use the project profile condition to include just the files, that are required to be in the component package.

**Comment by rpribyl** [comment]
This issue relates to a solution that has been completely redesigned.
At the moment there is no issue with including unwanted C# files into the component library because the component files are kept separately from the sandbox sample site
