### ISSUE TITLE
Make a proofreading of the readme

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-mvc-component-starter#4]
### Brief issue description

The [readme](https://github.com/Kentico/ems-mvc-component-boilerplate/blob/master/README.md) might contain some naming issues, typos, etc...

### Expected behavior

The readme wording has to be consistent with the documentation.
+ add the resources for the MVC widget development (proposals in the description of https://kentico.atlassian.net/browse/DCN-204)

**Comment by rpribyl** [comment]
Done here: https://github.com/Kentico/ems-mvc-component-starter/pull/6
